# Generated by Django 4.2.17 on 2024-12-15 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TxInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frequency", models.BigIntegerField()),
                ("dr", models.IntegerField()),
                (
                    "payload",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tx_info",
                        to="devices.payload",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RxInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gatewayID", models.CharField(max_length=16)),
                ("name", models.CharField(max_length=50)),
                ("time", models.DateTimeField()),
                ("rssi", models.IntegerField()),
                ("loRaSNR", models.FloatField()),
                (
                    "payload",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rx_info",
                        to="devices.payload",
                    ),
                ),
            ],
        ),
    ]
